# Generated by Django 3.2 on 2021-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
