# Generated by Django 3.2 on 2021-05-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_category_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pid',
        ),
    ]
