# Generated by Django 3.2 on 2021-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sinppest',
            field=models.CharField(default='Click link above to read blog', max_length=255),
        ),
    ]
