# Generated by Django 3.2 on 2021-04-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0007_post_sinppest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sinppest',
            new_name='snippet',
        ),
    ]
